server:
  port: 8087

spring:
  application:
    name: erp-pricing-service

# Swagger配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# 应用配置
app:
  name: 智能定价服务
  version: 1.5.0
  author: 火球鼠
